import = ["/home/smabbasht/.config/alacritty/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "Comic Mono NF"
style = "Bold"

[font.normal]
family = "Comic Mono NF"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/fish"

[window]
opacity = 0.75

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 8
y = 0
