general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "ComicShannsMono Nerd Font" }
bold = { family = "ComicShannsMono Nerd Font" }
italic = { family = "ComicShannsMono Nerd Font" }
size = 12

[window]
padding.x = 14
padding.y = 14
decorations = "None"

# [keyboard]
# bindings = [{ key = "F11", action = "ToggleFullscree4" }]
