# Application bindings

$terminal = uwsm app -- alacritty
$browser = uwsm app -- google-chrome-stable --new-window --ozone-platform=wayland
$webapp = $browser --app

bindd = SUPER, return, Terminal, exec, $terminal
bindd = SUPER, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER, M, Music, exec, uwsm app -- spotify
bindd = SUPER, N, Neovim, exec, $terminal -e nvim
bindd = SUPER, T, Activity, exec, $terminal -e btop
bindd = SUPER SHIFT, D, Docker, exec, $terminal -e lazydocker
# bindd = SUPER, G, Signal, exec, uwsm app -- signal-desktop
# bindd = SUPER, O, Obsidian, exec, uwsm app -- obsidian -disable-gpu
# bindd = SUPER, slash, Passwords, exec, uwsm app -- 1password

bindd = SUPER, A, ChatGPT, exec, $webapp="https://chatgpt.com"
bindd = SUPER SHIFT, A, Grok, exec, $webapp="https://grok.com"
bindd = SUPER, C, Calendar, exec, $webapp="https://app.hey.com/calendar/weeks/"
bindd = SUPER, E, Email, exec, $webapp="https://app.hey.com"
bindd = SUPER, Y, YouTube, exec, $webapp="https://youtube.com/"
bindd = SUPER SHIFT, G, WhatsApp, exec, $webapp="https://web.whatsapp.com/"
bindd = SUPER ALT, G, Google Messages, exec, $webapp="https://messages.google.com/web/conversations"
bindd = SUPER, X, X, exec, $webapp="https://x.com/"
bindd = SUPER SHIFT, X, X Post, exec, $webapp="https://x.com/compose/post"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, Space
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu

# smabbasht - bindings

bindd = SUPER, h, Move focus left, movefocus, l
bindd = SUPER, l, Move focus right, movefocus, r
bindd = SUPER, k, Move focus up, movefocus, u
bindd = SUPER, j, Move focus down, movefocus, d

bindd = SUPER SHIFT, h, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, l, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, k, Swap window up, swapwindow, u
bindd = SUPER SHIFT, j, Swap window down, swapwindow, d

bindd = SUPER, D, Launch apps, exec, walker -p "Start…"

bindd = SUPER, Q, Close active window, killactive,
