#!/usr/bin/env bash

languages=$(echo "git python c cpp dart bash" | tr " " "\n")
core_utils=$(echo "cat chmod chown cp cut date dd df du echo env expr false head id kill ln ls mkdir mv pwd rm rmdir sleep sort tee test touch true uname uniq wc yes awk sed grep find xargs" | tr " " "\n")
selected=$(echo -e "$languages\n$core_utils" | fzf)
read -p "Gimme your query: " query 

if echo "$languages" | grep -qs $selected; then 
    curl cht.sh/$selected/$(echo $query | tr " " "+") #| less --RAW-CONTROL-CHARS
else
    curl cht.sh/$selected~$(echo $query | tr " " "+") #| less --RAW-CONTROL-CHARS
fi


