version: "3"

services:
  app:
    image: tiryoh/ros-melodic-desktop
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
