yay -S alternatives
yay -S android-studio
yay -S anydesk-bin
yay -S archlinux-tweak-tool-git
yay -S beakerlib
yay -S brave-bin
yay -S cpu-checker-bzr
yay -S dict-wn
yay -S flutter
yay -S github-desktop-bin
yay -S i3-battery-popup
yay -S i3-resurrect
yay -S i3lock-color
yay -S i3lock-fancy-git
yay -S icat
yay -S mailspring
yay -S ncurses5-compat-libs
yay -S nerd-fonts-sf-mono
yay -S ninja-git
yay -S no-more-secrets
yay -S orchis-theme
yay -S perl-term-shellui
yay -S sddm-sugar-candy-git
yay -S sddm-sugar-dark
yay -S smem
yay -S spotify
yay -S spotify-adblock-git
yay -S spotifywm-git
yay -S stardict-wordnet
yay -S teams
yay -S yay
yay -S zoom
